### ISSUE TITLE
Incorrect defines in cub3d.h

### ISSUE THREAD

**Issue by AdrianWeaver** [Elena-Lou/Cub3D#12]
The norm does not allow to create a define as the result of a calculus.

Therefore the following defines are not allowed:
FOV (66 * PI / 180)
NORTH (3 * PI / 2)
SOUTH (PI / 2)

Should be replaced by:
FOV 1.151917306
NORTH 4.71238898
SOUTH 1.570796327

**Comment by AdrianWeaver** [comment]
You may fix this by cherry-picking 0d7276d on your branch.

**Comment by Elena-Lou** [comment]
Done ! Thank you for the correction
