### ISSUE TITLE
Segfault with player movement in key_check.c

### ISSUE THREAD

**Issue by AdrianWeaver** [Elena-Lou/Cub3D#13]
This is a minor error given the state of development of the project.
Writing it down to document it and keep it somewhere.

In function ft_key_check, in key_check.c

Movements could be improved by a function limiting it to positive values and HEIGHT / WIDTH comparisons.

**Comment by AdrianWeaver** [comment]
You may cherry-pick 53c0153 to fix it in your branch.

**Comment by Elena-Lou** [comment]
Done as well ! Thank you for the fix
