### ISSUE TITLE
Presence of "fd" in structure s_cub_data

### ISSUE THREAD

**Issue by AdrianWeaver** [Elena-Lou/Cub3D#3]
Is there a valid reason for the presence of the variable "fd" in struct s_cub_data ?

It seems that this variable is only used in function map_to_list that opens and closes the fd.

Therefore one may argue there is no use for it to be store in the structure.

**Comment by Elena-Lou** [comment]
Hey,

I agree. 
Before our use of a linked list to store the map lines, I had to split the function into smaller ones and I wanted to access the fd in both.

**Comment by AdrianWeaver** [comment]
Great will change this is aw/parse_map!
